# medical-rocker/tidyverse_ja のビルドと起動
# Suggests のパッケージまで含めた拡大版

version: "3"
services:
  rstudio:
    build:
      context: .
      dockerfile: Dockerfile_full
    image: "medical-rocker/tidyverse_ja:4.0.4_full"
    container_name: rstudio
    ports:
      - "8787:8787"
  # environment:
  #   PASSWORD: tidyverse
  #   DISABLE_AUTH: false
